language: cpp

sudo: required

services:
  - docker

script:
  - "curl -s https://raw.githubusercontent.com/bartoszek/arch-travis/signle-line-script/arch-travis.sh | bash"

arch:
  repos:
    - archlinuxcn=https://cdn.repo.archlinuxcn.org/$arch
  packages:
    # See *depends in https://github.com/archlinuxcn/repo/blob/master/archlinuxcn/qtermwidget-git/PKGBUILD
    - git
    - cmake
    - lxqt-build-tools-git
    - qt5-tools
    - python-pyqt5
    - python-sip
    - sip
  script: bash ./.ci/build.sh
